name: Deploy to Firebase

on:
  push:
    branches:
      - main  # このブランチに push されたときにデプロイを実行します

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.7.3'  # ローカルと同じNode.jsバージョンを指定

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools  # Firebase CLIをグローバルにインストール

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: firebase deploy --only hosting
